import React, {useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Sparkles, Heart, Users, Crown, Share2, ArrowRight, Star, Gift, ShieldCheck, ChevronRight, Check, X} from 'lucide-react';
import './styles.css';

const predictions={career:'A strong day for decisions. Trust your preparation and take one bold step toward a goal.',love:'Open conversations create warmth today. A small honest message can change the mood.',finance:'Pause before impulse spending. One practical decision today can improve your week.',energy:'Your focus is rising. Protect your best two hours from distractions.'};
const detailData={
  "Today's energy":{score:'82%',tag:'High focus',text:predictions.energy,extra:'Best window: 10 AM – 12 PM. Protect your focus and finish one important task before starting another.'},
  'Love forecast':{score:'76%',tag:'Warm',text:predictions.love,extra:'Connection tip: choose honesty over assumptions. A short, genuine conversation can strengthen a relationship today.'},
  Career:{score:'88%',tag:'Opportunity',text:predictions.career,extra:'Career tip: take one bold step today — send the application, share the idea, or start the task you have been postponing.'},
  Finance:{score:'64%',tag:'Be mindful',text:predictions.finance,extra:'Money tip: wait before impulse purchases and review one recurring expense this week.'}
};

function App(){
 const [page,setPage]=useState('home'); const [name,setName]=useState('Sai'); const [showModal,setShowModal]=useState(false); const [shared,setShared]=useState(false); const [detail,setDetail]=useState(null);
 const nav=(p)=>setPage(p);
 return <div className="app">
  <div className="stars s1"/><div className="stars s2"/>
  <header><div className="brand" onClick={()=>nav('home')}><span className="logo">✦</span><span>Astro<span>Circle</span></span></div><nav><button className={page==='home'?'active':''} onClick={()=>nav('home')}>Home</button><button onClick={()=>nav('circle')}>AstroCircle</button><button onClick={()=>nav('astrologers')}>Astrologers</button></nav><button className="profile" onClick={()=>nav('profile')}>S</button></header>
  {page==='home'&&<Home name={name} nav={nav} onStart={()=>setShowModal(true)} shared={shared} onDetails={setDetail}/>} 
  {page==='circle'&&<Circle nav={nav} onShare={()=>setShared(true)}/>} 
  {page==='astrologers'&&<Astrologers onBook={()=>setShowModal(true)}/>} 
  {page==='profile'&&<Profile name={name}/>} 
  {page==='premium'&&<Premium onClose={()=>nav('home')}/>} 
  {showModal&&<Onboard name={name} setName={setName} close={()=>setShowModal(false)} go={()=>{setShowModal(false);nav('home')}}/>}
  {detail&&<Details detail={detail} close={()=>setDetail(null)}/>} 
  <footer><span>✦ AstroCircle</span><span>Astrology for connection, reflection & discovery</span><span>Prototype • AstroHack 2026</span></footer>
 </div>
}

function Home({name,nav,onStart,shared,onDetails}){return <main>
 <section className="hero"><div className="pill"><Sparkles size={14}/> PERSONALIZED ASTROLOGY</div><h1>Discover your stars.<br/><em>Share your universe.</em></h1><p>Daily guidance, meaningful compatibility and shareable moments that turn astrology into a habit you look forward to.</p><div className="actions"><button className="primary" onClick={onStart}>Get my reading <ArrowRight size={17}/></button><button className="ghost" onClick={()=>nav('circle')}>Explore AstroCircle</button></div><div className="socialproof"><div className="avatars"><i>R</i><i>A</i><i>P</i><i>+</i></div><span><b>12,400+</b> circles created this week</span></div></section>
 <section className="dashboard"><div className="sectionhead"><div><small>WEDNESDAY • AUG 19</small><h2>Good afternoon, {name} ✨</h2></div><div className="streak"><span>🔥</span><b>7 day streak</b><small>+120 points</small></div></div>
 <div className="grid"><Card title="Today's energy" icon={<Sparkles/>} score="82%" text={predictions.energy} tag="High focus" onDetails={onDetails}/><Card title="Love forecast" icon={<Heart/>} score="76%" text={predictions.love} tag="Warm" onDetails={onDetails}/><Card title="Career" icon={<Star/>} score="88%" text={predictions.career} tag="Opportunity" onDetails={onDetails}/><Card title="Finance" icon={<Gift/>} score="64%" text={predictions.finance} tag="Be mindful" onDetails={onDetails}/></div>
 <div className="feature"><div className="featurecopy"><div className="pill soft"><Users size={14}/> YOUR ASTROCIRCLE</div><h2>See how your stars connect.</h2><p>Compare your cosmic energy with friends and discover what makes your connection unique.</p><button className="primary" onClick={()=>nav('circle')}>Check compatibility <ChevronRight size={17}/></button></div><div className="compat"><div className="rings"><span>♈</span><strong>92%</strong><span>♌</span></div><b>Sai & Rahul</b><small>Friendship compatibility</small></div></div>
 {shared&&<div className="toast"><Check size={16}/> Your AstroCard is ready to share!</div>}
 </section></main>}
function Card({title,icon,score,text,tag,onDetails}){return <div className="card"><div className="cardtop"><span className="icon">{icon}</span><span className="tag">{tag}</span></div><h3>{title}<b>{score}</b></h3><p>{text}</p><button className="link" onClick={()=>onDetails(detailData[title])}>View details <ArrowRight size={14}/></button></div>}
function Details({detail,close}){return <div className="modalbg" onClick={close}><div className="modal detailsmodal" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}><X/></button><div className="pill"><Sparkles size={14}/> PERSONALIZED INSIGHT</div><h2>{detail.tag} — {detail.score}</h2><p>{detail.text}</p><div className="detailbox"><b>✨ Today's guidance</b><p>{detail.extra}</p></div><button className="primary wide" onClick={close}>Got it <Check size={16}/></button></div></div>}
function Circle({nav,onShare}){return <main className="page"><div className="pageintro"><div><div className="pill"><Users size={14}/> ASTROCIRCLE</div><h1>Your people, <em>in the stars.</em></h1><p>Astrology becomes more fun when you experience it together.</p></div><button className="primary" onClick={()=>onShare()}> <Share2 size={16}/> Invite a friend</button></div><div className="circlegrid"><div className="bigcard"><div className="matchhead"><div className="person">S</div><div className="line"><span>YOU</span><div></div><span>RAHUL</span></div><div className="person gold">R</div></div><div className="score">92<span>%</span></div><h2>Cosmic Connection</h2><p>Your communication styles align beautifully. You bring the spark; Rahul brings the grounding energy.</p><div className="bars"><div><span>Communication</span><b>96%</b><i style={{width:'96%'}}/></div><div><span>Trust</span><b>91%</b><i style={{width:'91%'}}/></div><div><span>Energy</span><b>89%</b><i style={{width:'89%'}}/></div></div><button className="primary wide" onClick={()=>onShare()}>Create shareable AstroCard <Share2 size={16}/></button></div><div className="sidecard"><h3>Your circle</h3><p>3 connections</p>{['Rahul • 92%','Ananya • 87%','Priya • 81%'].map((x,i)=><div className="friend" key={x}><span className={'mini m'+i}>{x[0]}</span><span>{x.split(' • ')[0]}<small>{x.split(' • ')[1]} match</small></span><ChevronRight size={16}/></div>)}<button className="ghost wide">+ Add someone</button></div></div><div className="sharebanner"><div><Share2/><div><b>Turn one reading into a new user.</b><small>Share your result. Friends unlock their own free compatibility reading.</small></div></div><span>Viral loop →</span></div></main>}
function Astrologers({onBook}){return <main className="page"><div className="pageintro"><div><div className="pill"><Star size={14}/> EXPERT GUIDANCE</div><h1>Talk to someone <em>who gets it.</em></h1><p>AI-guided discovery, human expertise when you need deeper answers.</p></div></div><div className="astrogrid">{[['Maya Sharma','Relationship & Vedic Astrology','4.9','₹25/min','MS'],['Arjun Rao','Career & Finance Astrology','4.8','₹30/min','AR'],['Meera Iyer','Tarot & Life Guidance','4.9','₹20/min','MI']].map((a,i)=><div className="astro" key={a[0]}><div className="astroavatar">{a[4]}</div><div className="online">● Online</div><h3>{a[0]} <ShieldCheck size={15}/></h3><p>{a[1]}</p><div className="rating">★ {a[2]} <span>• 500+ sessions</span></div><div className="astrobottom"><b>{a[3]}</b><button className="primary" onClick={onBook}>Chat now</button></div></div>)}</div><div className="revenue"><Crown/><div><b>Premium Astro Report</b><p>30-day personalized forecast with expert + AI insights.</p></div><strong>₹199</strong><button className="primary" onClick={onBook}>Unlock</button></div></main>}
function Profile({name}){return <main className="page"><div className="profilehero"><div className="profilepic">S</div><div><div className="pill">✦ MEMBER</div><h1>{name}'s cosmic profile</h1><p>Virgo • Rohini • Earth energy</p></div></div><div className="stats"><div><b>7</b><span>Day streak</span></div><div><b>24</b><span>Readings</span></div><div><b>8</b><span>Connections</span></div><div><b>420</b><span>Circle points</span></div></div><div className="roadmap"><h2>Your weekly ritual</h2><div className="steps"><span className="done">✓</span><div><b>Daily prediction</b><small>Complete every morning</small></div><span className="done">✓</span><div><b>Check your circle</b><small>2 connections this week</small></div><span>3</span><div><b>Unlock weekly report</b><small>6 more points to go</small></div></div></div></main>}
function Premium({onClose}){return <div/>}
function Onboard({name,setName,close,go}){return <div className="modalbg"><div className="modal"><button className="close" onClick={close}><X/></button><div className="pill"><Sparkles size={14}/> YOUR COSMIC PROFILE</div><h2>Let's personalize your universe.</h2><p>Enter a few details to unlock your daily reading.</p><label>Your name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/></label><div className="twocol"><label>Date of birth<input type="date"/></label><label>Birth time<input type="time"/></label></div><label>Birth city<input placeholder="e.g. Vellore, India"/></label><button className="primary wide" onClick={go}>Reveal my reading <Sparkles size={16}/></button><small className="privacy">🔒 Your birth details stay private in this prototype.</small></div></div>}

createRoot(document.getElementById('root')).render(<App/>);
